### ISSUE TITLE
error: exec plugin: invalid apiVersion "client.authentication.k8s.io/v1alpha1

### ISSUE THREAD

**Issue by genieai-vikas** [zachguo/setup-eks-kubectl#7]
This action is not working anymore getting this issue:

```
error: exec plugin: invalid apiVersion "client.authentication.k8s.io/v1alpha1"
error: exec plugin: invalid apiVersion "client.authentication.k8s.io/v1alpha1"
```

**Comment by MStefanov** [comment]
The same case on my side

**Comment by genieai-vikas** [comment]
I found the fix. Use the below code in the Github action in the first step
```
      - uses: azure/setup-kubectl@v2.0
        with:
          version: v1.23.6 # default is latest stable
        id: install
```
